Add FaultConfiguration class
BP2022-AP1/bp2022-ap1 pull request #134
Opened 2023-03-30 11:35 UTC by instant-sky

Fixes #133 

Description (what might a PO or reviewer want to know?)

## PR checklist

- [ ] Acceptance criteria fulfilled
- [ ] Additional features are tested
- [ ] Docs (code, wiki & diagrams) updated
- [ ] Breaking changes anounced
- [ ] Dev-branch has been merged into local branch to resolve conflicts
- [ ] Tests and linter have passed AFTER local merge
- [ ] Another dev reviewed and approved

2023-03-30 12:42 UTC, Lietze approved these changes
Good job, every common attribute from the wiki is implemeted now.

2023-03-30 14:32 UTC, antonykamp approved these changes

2023-03-30 14:33 UTC, antonykamp requested changes

2023-03-30 14:33 UTC, antonykamp commented on src/fault_injector/fault_types/fault.py
> +class FaultConfiguration(BaseModel):
Missing function for serialization and deserialization 😇

2023-04-03 09:40 UTC, antonykamp reviewed
The class is looking pretty good now 🥳 
You wanna add tests? Or do you think its not necessary for this config? 🙃

2023-04-03 09:41 UTC, antonykamp commented on src/fault_injector/fault_types/fault.py
> +class FaultConfiguration(BaseModel):
Please add the FaultConfiguration class to the array of db-tables in `src/constants.py` 😇

2023-04-03 09:43 UTC, antonykamp commented on src/fault_injector/fault_types/fault.py
> +class FaultConfiguration(BaseModel):
Not needed, because FaultConfiguration should be abstract and not available as table.

2023-04-03 09:57 UTC, antonykamp approved these changes
Looking f*cking good now 🥳

2023-04-03 09:58 UTC, merged