Feature: Add schemas, tags and comments to OpenApi3 definition and update request collection
BP2022-AP1/bp2022-ap1 pull request #496
Opened 2023-05-23 08:00 UTC by antonykamp

Fixes #435 

Add schemas of requests and responses, tags and comments to OpenApi3 definition.
Remove interlocking route. Replace schedule route with individual routes for regular, random and demand schedules.
Update request collection.

## PR checklist

- [x] Acceptance criteria fulfilled
- [x] Additional features are tested
- [x] Docs (code, wiki & diagrams) updated
- [ ] Dev-branch has been merged into local branch to resolve conflicts
- [ ] Tests and linter have passed AFTER local merge
- [ ] Another dev reviewed and approved

2023-07-18 11:16 UTC, LucasDerReisende requested changes
index.yaml looks good, made some comments, most of them are typo related, some might be typo recommendations
I am also not up-to-date whether we are using tokens any longer, could they be removed or do they stay?
did not have a look into rest-api-autogenerate

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        It returns id connected to the simulation. Use this id to start a run.
the id

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +          description: Token is missing
do we still use tokens?

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +          description: Simulation configuration is used in a run
by a run?

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Specify the gap with the field 'regular_strategy_frequency'
fields won't be displayed as monospace

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Use 'inject_probability' and 'resolve_probability' to adjust the probability of the schedule becoming active.
do we have inject_probability, resolve_probability for schedules?

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        the starting tick and ending tick of the schedule and the injection and resolve possibility.
schedules are not injected and resolved

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        speakable_id:
what is a speakable_id, it is not used in code. If it should represent a readable_id, then it is only displayed with regular, random and demand schedules

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Use 'train_schedule_train_type' to select this even more by defining the train type (Coal or passenger trains)
Should there maybe be parameters, because it is just a text in the docs

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Specify the probability with the field 'random_strategy_trains_per_1000_ticks'
no displayed in monospace

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Use 'inject_probability' and 'resolve_probability' to adjust the probability of the schedule becoming active.
not used

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Use 'train_schedule_train_type' to select this even more by defining the train type (Coal or passenger trains)
missing period, Coal -> coal

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        the starting tick and ending tick of the schedule and the injection and resolve possibility.
no inject/resolve probability

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        The schedule decides to spawn a train based on data from the Bundesnetzagentur
replace with 'The schedule decides to spawn trains based on data of the Federal Network Agency'

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        If you want to read more, take a look at https://github.com/BP2022-AP1/bp2022-ap1/wiki/Coal-Consumption.
can this be a hyperlink?

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        You must also define the interval where the schedule should be active with 'start_tick' and 'end_tick.'
not monospace, period behind quote

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Use 'inject_probability' and 'resolve_probability' to adjust the probability of the schedule becoming active.
no inject/resolve probability

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Use 'train_schedule_train_type' to select this even more by defining the train type (Coal or passenger trains).
can there be a paragraphs in the text, because it looks like a large block of text in the documentation?

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        the starting tick and ending tick of the schedule and the injection and resolve possibility.
no inject/resolve probability

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Insert a new schedule-blocked-fault component. It returns the id of the
Should it be component -> configuration?

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        A schedule-blocked fault prohibits a train from a schedule to spawning for some time.
please rewrite this sentence, I do not understand

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Set the injection probability and resolve the fault with 'inject_probability' and 'resolve_probability'id.
.. and resolution probability of the fault with 'inject_probability' and 'resolve_probability'.

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Additionally, you can set a fault injection, either regular or random, with the field 'strategy'.
can you really do this?

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        This includes the stategy, starting tick, ending tick, injection and resolve propability and the affected element id.
strategy, resolution probability

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +            Specify id of simulation if you only want to get the spawner
... specify _the_ id ..., also change it in other places

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Insert a new track-blocked-fault component. It returns the id of the
component -> configuration?

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        A track-blocked fault blocks a track on the rails system for an some time.
rails system -> rail system
for an some time?

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        You define the affected track with the field 'affected_element_id'.
not monospace

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Set the injection probability and resolve the fault with 'inject_probability' and 'resolve_probability'id.
same comments as before with this sentence, see l. 759

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        This includes the stategy, starting tick, ending tick, injection and resolve propability and the affected element id.
change stategy -> strategy, probability with b, check everywhere you encounter this error, I will not mark everyone

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +      summary: Get ids of track-speed-limit-fault configurations. Use this in the simulation configuration.
get the ids of ..

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Insert a new track-speed-limit-fault component. It returns the id of the
component -> configuration

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Set the temporal speed limit with 'new_speed'.
what is a temporal speed limit?

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Set the injection probability and resolve the fault with 'inject_probability' and 'resolve_probability'id.
l. 759

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        This includes the stategy, starting tick, ending tick, injection and resolve propability, the affected element id and the new speed limit.
strategy, resolution probability

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +      summary: Insert a new train-prio-fault component. It returns the id of the
configuration

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        A train-prio fault edits the priority  of a train for some time.
two spaces, ... for a specified peroid of time.

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Set the temporal priority  with 'new_prio'.
two spaces

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Set the injection probability and resolve the fault with 'inject_probability' and 'resolve_probability'id.
l. 759

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        This includes the stategy, starting tick, ending tick, injection and resolve propability, the affected element id and the new prio.
strategy, resolution probability

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +            Specify id of simulation if you only want to get the train-speed-fault
the id of the simulation?

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Insert a new train-speed-fault component. It returns the id of the
configuration

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        A train-speed fault edits the maximum speed of a train for some time.
for a specified period of time

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        You define the affected train with the field 'affected_element_id'.
monospace

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Set the injection probability and resolve the fault with 'inject_probability' and 'resolve_probability'id.
l. 759

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        This includes the stategy, starting tick, ending tick, injection and resolve propability, the affected element id and the new speed.
strategy, resolution probability

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +      summary: Get ids of platform-blocked-fault configurations. Use this in the simulation configuration.
get the ids of

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Insert a new platform-blocked-fault component. It returns the id of the
configuration

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        A platform-blocked fault blocks a platform for trains for some time.
specified period of time

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        Set the injection probability and resolve the fault with 'inject_probability' and 'resolve_probability'id.
l. 759

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        This includes the stategy, starting tick, ending tick, injection and resolve propability and the affected element id.
strategy, resolution probability

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
>          Create new token with specified permission specified in body if current
Create a new token

2023-07-18 11:16 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +          description: Token is missing
apparently

2023-07-18 13:06 UTC, antonykamp commented on postman/schemas/index.yaml
> +        Use 'inject_probability' and 'resolve_probability' to adjust the probability of the schedule becoming active.
no upsi :D

2023-07-18 13:07 UTC, antonykamp commented on postman/schemas/index.yaml
> +        Use 'train_schedule_train_type' to select this even more by defining the train type (Coal or passenger trains)
They are referenced in the schema too 😇

2023-07-18 13:09 UTC, antonykamp commented on postman/schemas/index.yaml
> +        If you want to read more, take a look at https://github.com/BP2022-AP1/bp2022-ap1/wiki/Coal-Consumption.
apperently not :(

2023-07-18 13:09 UTC, antonykamp commented on postman/schemas/index.yaml
> +        Use 'train_schedule_train_type' to select this even more by defining the train type (Coal or passenger trains).
Apparently not :(

2023-07-18 13:12 UTC, antonykamp commented on postman/schemas/index.yaml
> +        Additionally, you can set a fault injection, either regular or random, with the field 'strategy'.
yes :D

2023-07-18 13:25 UTC, antonykamp commented on postman/schemas/index.yaml
> +          description: Token is missing
yes :D

2023-07-21 09:14 UTC, LucasDerReisende requested changes
Looks good imo, I just do not understand, that a run does not have a readable_id. Is this intended, because we use those readable_ids in the dashboard later

2023-07-21 09:23 UTC, antonykamp commented
>  I just do not understand, that a run does not have a readable_id. Is this intended, because we use those readable_ids in the dashboard later

That's a good point 😂 We currently don't return the readable_id of a run. 🤔 I'll create an issue for that and add it to the documentation 👍

2023-07-21 09:37 UTC, LucasDerReisende commented
Gracias!

2023-07-21 09:37 UTC, LucasDerReisende approved these changes
Looks good now :)

2023-07-21 10:05 UTC, LucasDerReisende commented on postman/schemas/index.yaml
> +        speakable_id:
Should be fixed

2023-07-21 10:06 UTC, merged