Feature/logging on `simulation_objects`
BP2022-AP1/bp2022-ap1 pull request #544
Opened 2023-06-12 06:44 UTC by SaturnHafen

Fixes #25 

I added the event bus calls in the corresponding places and tested them using mocks.

I merged #538 already to get the (new) timetable logic.

## PR checklist

- [x] Acceptance criteria fulfilled
- [x] Additional features are tested
- [ ] ~~Docs (code, wiki & diagrams) updated~~
- [ ] ~~Breaking changes anounced~~
- [ ] ~~Added classes that inherit from `BaseModel` to `src.constants.tables`~~
- [ ] Dev-branch has been merged into local branch to resolve conflicts
- [ ] Tests and linter have passed AFTER local merge
- [ ] Another dev reviewed and approved

2023-06-27 05:19 UTC, antonykamp approved these changes
I'm sorry for the long delay 😄 I forgot it somehow.
It's a big PR with many changes, but it looks fine to me 👍 
Thanks for your work 💚

2023-07-24 12:01 UTC, SaturnHafen commented
The failing tests are something @Lietze has added. I don't know how to fix them.

2023-07-25 11:45 UTC, Lietze requested changes
Hey this looks good now, but I think one more change is needed

2023-07-25 11:45 UTC, Lietze commented on src/interlocking_component/route_controller.py
> +        train.reserved_tracks.pop(0)
Why is this in this PR? By now is is handled in the infrastructure provider which calls the RouteController.

2023-07-25 11:49 UTC, Lietze approved these changes
Good job

2023-07-25 12:26 UTC, merged